
# /api-gateway/config/nginx.conf

events {}

http {
    server {
        listen 80;
        server_name localhost;

        # Rota para servir os arquivos estáticos do frontend (React/Vite)
        # Esta é a configuração padrão para uma Single Page Application (SPA)
        location / {
            # Caminho onde os arquivos do build do frontend estarão na imagem Docker
            root /usr/share/nginx/html;
            index index.html;
            # Se um arquivo ou diretório não for encontrado, ele serve o index.html
            # Isso permite que o roteador do React (React Router) controle as rotas no lado do cliente.
            try_files $uri $uri/ /index.html;
        }

        # Rota para o proxy reverso da API de backend
        location /load-tester/ {
            # O nome do serviço 'loadtest-api-svc' e a porta '4000' devem corresponder ao serviço da API no Kubernetes
            proxy_pass http://loadtest-api-svc:4000/;

            # Cabeçalhos importantes para passar para a aplicação de backend
            # Eles garantem que a aplicação saiba a origem real da requisição
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/ {
            proxy_pass http://orchestror-api-svc:5000/;

            
            proxy_set_header Host $host;
            proxy_set_header X-REAL-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

        }
    }
}
