apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtest-api
spec:
  selector:
    matchLabels:
      app: loadtest-api
  template:
    metadata:
      labels:
        app: loadtest-api
    spec:
      containers:
      - name: loadtest-api
        image: luisffilho/load-tester-api:20250818
        ports:
        - containerPort: 4000
        env:
        - name: API_PORT
          value: "4000"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_HOST
          value: "redis-svc"
        - name: MONGODB_URI
          value: "mongodb://mongo-svc:27017/load-tester-db"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
