apiVersion: v1
kind: Service
metadata:
  name: loadtest-worker-svc
spec:
  selector:
    app: loadtest-worker
  type: NodePort
  ports:
  - protocol: TCP
    port: 9100
    targetPort: 9100