apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtest-worker
spec:
  selector:
    matchLabels:
      app: loadtest-worker
  template:
    metadata:
      labels:
        app: loadtest-worker
    spec:
      containers:
      - name: loadtest-worker
        image: luisffilho/load-tester-worker:latest
        env:
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_HOST
          value: "redis-svc"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"