apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-api
spec:
  selector:
    matchLabels:
      app: orchestrator-api
  template:
    metadata:
      labels:
        app: orchestrator-api
    spec:
      containers:
      - name: orchestrator-api
        image: luisffilho/health-check-api:20250829
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-svc:27017/health-check-db"
        - name: REDIS_HOST
          value: "redis-svc"
        - name: REDIS_PORT
          value: "6379"
        - name: CRON_SCHEDULE
          value: "60000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"