apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtest-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtest-app
  template:
    metadata:
      labels:
        app: loadtest-app
    spec:
      containers:
      - name: loadtest-app
        image: luisffilho/load-tester-app:latest # <- E esta também!
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        ports:
        - containerPort: 5173